### ISSUE TITLE
MRSS-bot-web not surviving restart

### ISSUE THREAD

**Issue by Griefed** [synzen/MonitoRSS-Clone#19]
Hello synzen,

I've been having trouble setting up my own container for MonitoRSS-Clone and was wondering whether you would be able to help me out.
I am starting my containers with a compose like this:
```yml
version: "3.5"
services:
  mrss-redis:
    container_name: mrss-redis
    restart: unless-stopped
    image: redis:alpine
    networks:
      - default
  mrss-mongo:
    container_name: mrss-mongodb
    restart: unless-stopped
    command: mongod --port 27017
    image: mongo:latest
    volumes:
      - ./db:/data/db
    networks:
      - default
  mrss-bot-web:
    container_name: mrss-bot-web
    restart: unless-stopped
    image: griefed/monitorss-clone:develop
    depends_on:
      - mrss-mongo
      - mrss-redis
    environment:
      - TZ=Europe/Berlin
      - PUID=1003
      - PGID=998
      - DRSS_START=bot-web
      - DRSS_BOT_TOKEN=[REDACTED]
      - DRSS_DATABASE_URI=mongodb://mrss-mongo:27017/rss
      - DRSS_BOT_PREFIX=~
      - DRSS_BOT_OWNERIDS=[REDACTED]
      - DRSSWEB_DATABASE_URI=mongodb://mrss-mongo:27017/rss
      - DRSSWEB_DATABASE_REDIS=redis://mrss-redis:6379
      - DRSSWEB_ADMINIDS=[REDACTED]
      - DRSSWEB_BOT_TOKEN=[REDACTED]
      - DRSSWEB_BOT_REDIRECTURI=[REDACTED]
      - DRSSWEB_BOT_CLIENTID=[REDACTED]
      - DRSSWEB_BOT_CLIENTSECRET=[REDACTED]
      - DRSSWEB_SESSION_SECRET=[REDACTED]
    networks:
      - default

networks:
  default:
    external:
      name: prosper
```

And it all works fine. The bot comes online, the webinterface comes online and I can use it with a reverse proxy. All fine and good. However, after restart mrss-bot-web, the webinterface no longer comes online and I've been trying to figure out how and why that is.

EDIT:
After restarting the container, this is all I get:
> [2021-01-30 18:22:52.033 +0100] INFO    : [W] Attempting to connect to databases...
[2021-01-30 18:22:52.091 +0100] INFO    : [WM] Connected to MongoDB
[2021-01-30 18:22:52.157 +0100] INFO    : [WM] Connected to Redis
[2021-01-30 18:22:52.161 +0100] INFO    : [W] Databases connected
[2021-01-30 18:22:53.166 +0100] INFO    : [-] Connected to Redis
[2021-01-30 18:22:59.219 +0100] INFO    : [0] MonitoRSS has logged in as [REDACTED]
[2021-01-30 18:22:59.744 +0100] INFO    : [0] Database URI detected as a MongoDB URI
[2021-01-30 18:22:59.764 +0100] INFO    : [0] Commands have been enabled.
[2021-01-30 18:22:59.766 +0100] INFO    : [M] All shards have initialized by the Sharding Manager.
[2021-01-30 18:22:59.769 +0100] INFO    : [M] Started fetch intervals
[2021-01-30 18:22:59.783 +0100] INFO    : [default] Finished feed retrieval cycle. No feeds to retrieve
[2021-01-30 18:23:09.608 +0100] INFO    : [-] MonitoRSS-Web logged in as [REDACTED]

After the last line, it just seems to stop.

There are no errors indicating that anything went wrong. I've tried:
- Using a mounted volume like in the example docker-compose from your repository
- Running the bot and webinterface in separate containers
- Writing all environment variables to the config.bot and config.web.json files so the container(s) do not need to rely on the environment variables being set

I feel like I'm missing something obvious here, but I don't know what it is. 
Any help, if possible, would be greatly appreciated. I've been looking for a selfhosted RSS-Feed-To-Discord software for a couple of weeks and yours looks and feels brilliant to use.

Stay safe and stay awesome.

Cheers,
Griefed
